server:
  port: 8082
  forward-headers-strategy: framework

spring:
  application:
    name: auth-service
  config:
    import: optional:file:../../application-secrets.yml
  datasource:
    url: jdbc:mysql://qma-database.c9qcc20w0lz6.ap-south-1.rds.amazonaws.com:3306/auth_db?createDatabaseIfNotExist=true
    username: admin
    password: "05052005"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            # FIXED: Matches uppercase names in your EC2 .env file
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "http://43.205.228.140.nip.io:8085/login/oauth2/code/google"

jwt:
  # FIXED: Matches JWT_SECRETKEY in your EC2 .env file
  secretkey: ${JWT_SECRETKEY}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: "http://zipkin:9411/api/v2/spans"
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"
  endpoint:
    health:
      show-details: always