server:
  port: 8082
  forward-headers-strategy: framework

spring:
  application:
    name: auth-service

  config:
    import: optional:file:../../application-secrets.yml

  datasource:
    # UPDATED: Using AWS RDS Endpoint
    url: jdbc:mysql://qma-database.c9qcc20w0lz6.ap-south-1.rds.amazonaws.com:3306/auth_db?createDatabaseIfNotExist=true
    username: admin
    password: "05052005"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: "{baseUrl}/login/oauth2/code/google"

jwt:
  secretkey: ${jwt.secretkey}

eureka:
  client:
    service-url:
      # UPDATED: Using Docker service name
      defaultZone: http://eureka-server:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: "http://zipkin:9411/api/v2/spans"
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"
  endpoint:
    health:
      show-details: always