services:
  eureka-server:
    image: abhays2004/qma-eureka:latest
    ports:
      - "8761:8761"
    deploy:
      resources:
        limits:
          memory: 400M

  api-gateway:
    image: abhays2004/qma-gateway:latest
    ports:
      - "8085:8080"
    depends_on:
      - eureka-server
    deploy:
      resources:
        limits:
          memory: 700M

  auth-service:
    image: abhays2004/qma-auth:latest
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://qma-database.c9qcc20w0lz6.ap-south-1.rds.amazonaws.com:3306/auth_db?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=05052005
      # Values are injected by the Jenkins 'environment' block
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - JWT_SECRETKEY=${JWT_SECRETKEY}
    depends_on:
      - eureka-server
    deploy:
      resources:
        limits:
          memory: 1G

  qma-service:
    image: abhays2004/qma-service:latest
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://qma-database.c9qcc20w0lz6.ap-south-1.rds.amazonaws.com:3306/qma_db?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=05052005
      # Value is injected by the Jenkins 'environment' block
      - JWT_SECRETKEY=${JWT_SECRETKEY}
    depends_on:
      - eureka-server
    deploy:
      resources:
        limits:
          memory: 1G

  frontend:
    image: abhays2004/qma-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - api-gateway
    deploy:
      resources:
        limits:
          memory: 200M