server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      httpclient:
        connect-timeout: 10000
        response-timeout: 10s
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins:
              - "http://localhost:3000"
              - "http://localhost:5173"
              - "http://43.205.228.140.nip.io"
              - "http://43.205.228.140"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      # FIXED: Corrected indentation for routes
      routes:
        - id: auth-service-route
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**, /oauth2/**, /login/oauth2/code/**
          filters:
            - TokenRelay= # Ensures JWT is passed if using Spring Security
        
        - id: qma-service-route
          uri: lb://QMA-SERVICE
          predicates:
            - Path=/api/v1/quantities/**

eureka:
  client:
    registry-fetch-interval-seconds: 2
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: "http://zipkin:9411/api/v2/spans"
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"