server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins:
              - "http://localhost:3000"
              - "http://localhost:5173"
              - "http://43.205.228.140.nip.io"
              - "http://43.205.228.140"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: auth-service-route
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
        - id: qma-service-route
          uri: lb://QMA-SERVICE
          predicates:
            - Path=/api/v1/quantities/**
        - id: google-auth-init-route
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/oauth2/**
        - id: google-callback-route
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/login/oauth2/code/**
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: "http://zipkin:9411/api/v2/spans"
  endpoints:
    web:
      exposure:
        include: "health,info,metrics"
  endpoint:
    health:
      show-details: always